services:
  mysql:
    image: mysql:8.4
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ${VOLUME_PATH}/backup:/backup
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=secret-password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10

  backup:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=secret-password
      - MAX_BACKUPS=1
      - INIT_BACKUP=1
      - CRON_TIME=* * * * *
    restart: unless-stopped

volumes: 
  mysql-data:
